version: '2'
services:
  logstash:
    build:
      context: config/logstash/
    container_name: logstash
    ports:
      - 5044:5044
    volumes:
      - ./config/logstash/config/:/usr/share/logstash/config/
      - ./config/logstash/pipeline/:/usr/share/logstash/pipeline/
    environment:
      ELASTICSEARCH_HOST: https://vpc-edu-logging-elasticsearch-5jn2vhouuci3qqnzpf4w4mwyeq.ap-northeast-1.es.amazonaws.com:443
      LOG_INDEX_NAME: logstash-json-logs

