version: '2'
services:
#  dockerize-spring:
#    build: .
#    container_name: dockerize-spring
#    ports:
#      - 8080:8080
#    networks:
#      - spring-cloud-network
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.2
    container_name: logstash
    ports:
      - 5044:5044
    volumes:
      - ./config/logstash/config/:/usr/share/logstash/config/
      - ./config/logstash/pipeline/:/usr/share/logstash/pipeline/
    depends_on:
      - elasticsearch
    links:
      - elasticsearch