variable "ENV" {}
variable "PREFIX" {}
variable "SUBNET_IDS" {}
variable "SECURITY_GROUPS" {}
variable "VPC_ID" {}
variable "AWS_REGION" {}
variable "ES_INSTANCE" {}
variable "ES_VOLUME_GB" {}
variable "ES_ENCRYPTION" {}
variable "NGINX_SECURITY_GROUPS" {}
variable "NGINX_SUBNET_ID" {}
variable "NGINX_INSTANCE" {}
variable "NGINX_VOLUME_GB" {}
variable "NGINX_KEY" {}
variable "SPRING_SUBNET_ID" {}
variable "SPRING_SECURITY_GROUP" {}
variable "SPRING_INSTANCE" {}
variable "SPRING_VOLUME_GB" {}
variable "SPRING_KEY" {}
variable "DEFAULT_TAGS" {}
