FROM docker.elastic.co/logstash/logstash:7.7.0

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

RUN logstash-plugin install logstash-output-amazon_es